# Generated by Django 3.0 on 2023-03-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofadding', models.DateTimeField(auto_now_add=True)),
                ('previewimg', models.FileField(null=True, upload_to='')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location')),
            ],
        ),
    ]
